from pathlib import Path

path = Path("Packages/com.darumappap.my-unity-mcp/Editor/UnityGraphicsMcpAdaptiveProbeVolumeBake.cs")
text = path.read_text(encoding="utf-8")
old = """\t\t\t\t\tif (!environmentResolved)\n\t\t\t\t\t{\n\t\t\t\t\t\tUnityGraphicsMcpToolResult unsupported = CreateResult(\n\t\t\t\t\t\t\t\"graphics.prepare_apv_bake_plan\",\n\t\t\t\t\t\t\trequestId,\n\t\t\t\t\t\t\tE_MCP_TOOL_STATUS.BACKEND_NOT_IMPLEMENTED,\n\t\t\t\t\t\t\tfailureMessage,\n\t\t\t\t\t\t\tnew Dictionary<string, object>\n\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t{ \"failureCode\", failureCode },\n\t\t\t\t\t\t\t\t{ \"bakingSetAssetPath\", input.bakingSetAssetPath },\n\t\t\t\t\t\t\t\t{ \"lightingScenario\", input.lightingScenario }\n\t\t\t\t\t\t\t});\n\t\t\t\t\t\tunsupported.issues.Add(new UnityGraphicsMcpIssue\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\tcode = failureCode,\n\t\t\t\t\t\t\tmessage = failureMessage,\n\t\t\t\t\t\t\tevidence = unsupported.data\n\t\t\t\t\t\t});\n\t\t\t\t\t\treturn unsupported;\n\t\t\t\t\t}\n\n\t\t\t\t\tList<string> explicitScenes = input.scenePaths\n"""
new = """\t\t\t\t\tif (!environmentResolved)\n\t\t\t\t\t{\n\t\t\t\t\t\tUnityGraphicsMcpToolResult unsupported = CreateResult(\n\t\t\t\t\t\t\t\"graphics.prepare_apv_bake_plan\",\n\t\t\t\t\t\t\trequestId,\n\t\t\t\t\t\t\tE_MCP_TOOL_STATUS.BACKEND_NOT_IMPLEMENTED,\n\t\t\t\t\t\t\tfailureMessage,\n\t\t\t\t\t\t\tnew Dictionary<string, object>\n\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t{ \"failureCode\", failureCode },\n\t\t\t\t\t\t\t\t{ \"bakingSetAssetPath\", input.bakingSetAssetPath },\n\t\t\t\t\t\t\t\t{ \"lightingScenario\", input.lightingScenario }\n\t\t\t\t\t\t\t});\n\t\t\t\t\t\tunsupported.issues.Add(new UnityGraphicsMcpIssue\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\tcode = failureCode,\n\t\t\t\t\t\t\tmessage = failureMessage,\n\t\t\t\t\t\t\tevidence = unsupported.data\n\t\t\t\t\t\t});\n\t\t\t\t\t\treturn unsupported;\n\t\t\t\t\t}\n\n\t\t\t\t\tbool supportedPipeline = string.Equals(\n\t\t\t\t\t\tenvironment.PipelineKind,\n\t\t\t\t\t\t\"URP\",\n\t\t\t\t\t\tStringComparison.Ordinal) ||\n\t\t\t\t\t\tstring.Equals(\n\t\t\t\t\t\t\tenvironment.PipelineKind,\n\t\t\t\t\t\t\t\"HDRP\",\n\t\t\t\t\t\t\tStringComparison.Ordinal);\n\t\t\t\t\tif (!supportedPipeline)\n\t\t\t\t\t{\n\t\t\t\t\t\treturn CreateResult(\n\t\t\t\t\t\t\t\"graphics.prepare_apv_bake_plan\",\n\t\t\t\t\t\t\trequestId,\n\t\t\t\t\t\t\tE_MCP_TOOL_STATUS.UNSUPPORTED,\n\t\t\t\t\t\t\t\"APV BakeはURPまたはHDRP Pipelineでのみ準備できます。\",\n\t\t\t\t\t\t\tnew Dictionary<string, object>\n\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t{ \"failureCode\", \"UNSUPPORTED_PIPELINE\" },\n\t\t\t\t\t\t\t\t{ \"pipelineKind\", environment.PipelineKind },\n\t\t\t\t\t\t\t\t{ \"pipelineAssetType\", environment.PipelineAssetType },\n\t\t\t\t\t\t\t\t{ \"supportedPipelines\", new[] { \"URP\", \"HDRP\" } }\n\t\t\t\t\t\t\t});\n\t\t\t\t\t}\n\n\t\t\t\t\tList<string> explicitScenes = input.scenePaths\n"""
count = text.count(old)
if count != 1:
    raise SystemExit(f"Expected one APV environment block, found {count}")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
